Clustering

https://scikit-learn.org/stable/modules/clustering.html

In [1]:
import numpy as np
from sklearn.cluster import KMeans

X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0], [9,9], [100,100], [2,9],[-5,-8], [0,0]])
X

array([[  1,   2],
       [  1,   4],
       [  1,   0],
       [ 10,   2],
       [ 10,   4],
       [ 10,   0],
       [  9,   9],
       [100, 100],
       [  2,   9],
       [ -5,  -8],
       [  0,   0]])

In [2]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

In [3]:
kmeans.labels_

array([2, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2], dtype=int32)

In [4]:
import pandas as pd
df=pd.DataFrame(X)
df

0    1
0     1    2
1     1    4
2     1    0
3    10    2
4    10    4
5    10    0
6     9    9
7   100  100
8     2    9
9    -5   -8
10    0    0

In [5]:
df["label"]= kmeans.labels_
df

0    1  label
0     1    2      2
1     1    4      2
2     1    0      2
3    10    2      0
4    10    4      0
5    10    0      0
6     9    9      0
7   100  100      1
8     2    9      0
9    -5   -8      2
10    0    0      2

In [6]:
kmeans.predict([[3, 3],  # ? 
                [99, 99]])  # ?

array([2, 1], dtype=int32)

In [7]:
kmeans.cluster_centers_

array([[  8.2,   4.8],
       [100. , 100. ],
       [ -0.4,  -0.4]])

In [8]:
from sklearn.datasets import load_boston

In [9]:
boston= load_boston()

In [10]:
X= boston.data

In [11]:
X.shape

(506, 13)

In [12]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [13]:
kmeans = KMeans(n_clusters=5, random_state=0).fit(X)
kmeans.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4,
       4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 4, 0,
       4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 0, 4, 4, 4, 4, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2,
       2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4,

In [14]:
kmeans.cluster_centers_

array([[ 1.96320727e+00,  1.77635684e-15,  1.67081818e+01,
         9.09090909e-02,  7.07727273e-01,  5.91609091e+00,
         9.18181818e+01,  2.32369091e+00,  4.72727273e+00,
         3.86909091e+02,  1.70000000e+01,  1.87546364e+02,
         1.72127273e+01],
       [ 1.09105113e+01,  5.32907052e-15,  1.85725490e+01,
         7.84313725e-02,  6.71225490e-01,  5.98226471e+00,
         8.99137255e+01,  2.07716373e+00,  2.30196078e+01,
         6.68205882e+02,  2.01950980e+01,  3.71803039e+02,
         1.78740196e+01],
       [ 2.35398154e-01,  1.72596154e+01,  6.70953846e+00,
         7.69230769e-02,  4.84571923e-01,  6.47326538e+00,
         5.60657692e+01,  4.83767308e+00,  4.33846154e+00,
         2.74688462e+02,  1.78615385e+01,  3.88775654e+02,
         9.46638462e+00],
       [ 1.63460857e+01, -5.32907052e-15,  1.81000000e+01,
         1.38777878e-17,  6.66828571e-01,  6.07600000e+00,
         9.01257143e+01,  1.98833429e+00,  2.40000000e+01,
         6.66000000e+02,  2.02000000e


Q1
Cluster following X data to 4 clusters

```
# This is formatted as code
X = np.array([[11, 2], [1, 1], [0, 0], [1, 2],[5, 5], [11, 12], [10, 4], [10, 8]])
```



Clustering IRIS dataset

In [15]:
from sklearn.datasets import load_iris
iris= load_iris()

In [16]:
data= iris.data

In [17]:
data.shape

(150, 4)

In [18]:
kmeans = KMeans(n_clusters=5, random_state=0).fit(data)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 4, 4, 4, 3, 4, 4, 4, 3, 4, 3, 3, 4, 3, 4, 3, 4,
       4, 3, 4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 4, 3, 4, 4, 4,
       3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 1, 4, 2, 1, 1, 2, 3, 2, 1, 2,
       1, 1, 1, 4, 1, 1, 1, 2, 2, 4, 1, 4, 2, 4, 1, 2, 4, 4, 1, 2, 2, 2,
       1, 4, 4, 2, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 4], dtype=int32)

In [19]:
kmeans.cluster_centers_

array([[5.006     , 3.428     , 1.462     , 0.246     ],
       [6.52916667, 3.05833333, 5.50833333, 2.1625    ],
       [7.475     , 3.125     , 6.3       , 2.05      ],
       [5.508     , 2.6       , 3.908     , 1.204     ],
       [6.20769231, 2.85384615, 4.74615385, 1.56410256]])

Reducing Dimentionality and clustering

In [20]:
from sklearn.datasets import load_boston
boston= load_boston()

In [21]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [22]:
boston.data.shape

(506, 13)

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
boston2D=pca.fit_transform(boston.data)

In [24]:
boston2D

array([[-119.81884272,   -5.56005586],
       [-168.89015548,   10.11620863],
       [-169.31170747,   14.0805323 ],
       ...,
       [-138.38716306,    0.9380922 ],
       [-137.50517338,    4.2518251 ],
       [-139.19033295,    1.00906423]])

In [25]:
boston2D.shape

(506, 2)

In [26]:
kmeans = KMeans(n_clusters=5, random_state=0).fit(boston2D)
kmeans.labels_[100]

3

# Test Questions
Index starts from 0, if I say 30 you should look at array[30] or labels[30]

1. Cluster iris dataset into the 7 clusters (set random_state=0). What will be the cluster label of the 20th flower (index starting from 0), see labels[20].

2. Cluster iris dataset into the 7 clusters (set random_state=0). What will be the first value of the first cluster center vector (kmeans.cluster_centers_).

3. Cluster boston dataset into 5 cluster (set random_state=0). What will be the cluster label of the 100th house (please look at labels[100]).

4. Cluster boston dataset into the 5 clusters (set random_state=0). What will be the first value of the first cluster center vector (please see kmeans.cluster_centers_).


5. Reduce boston dataset into 3 components by PCA. And apply kmeans (random_state=0) for 4 clusters. what will be the cluster label of the 10th house (see labels[10]).



In [27]:
#Q1
import numpy as np
from sklearn.cluster import KMeans

from sklearn.datasets import load_iris
iris= load_iris()

kmeans = KMeans(n_clusters=7, random_state=0).fit(iris.data)
kmeans.labels_

array([1, 6, 6, 6, 1, 1, 6, 1, 6, 6, 1, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1,
       6, 1, 6, 6, 1, 1, 1, 6, 6, 1, 1, 1, 6, 6, 1, 1, 6, 1, 1, 6, 6, 1,
       1, 6, 1, 6, 1, 6, 5, 5, 5, 2, 5, 2, 5, 2, 5, 2, 2, 2, 2, 5, 2, 5,
       2, 2, 5, 2, 3, 2, 3, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 3, 2, 5, 5, 5,
       2, 2, 2, 5, 2, 2, 2, 2, 2, 5, 2, 2, 4, 3, 0, 4, 4, 0, 2, 0, 4, 0,
       4, 3, 4, 3, 3, 4, 4, 0, 0, 3, 4, 3, 0, 3, 4, 0, 3, 3, 4, 0, 0, 0,
       4, 3, 3, 0, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3], dtype=int32)

In [28]:
kmeans.labels_[20]

1

In [29]:
#Q2
import numpy as np
from sklearn.cluster import KMeans

from sklearn.datasets import load_iris
iris= load_iris()

kmeans = KMeans(n_clusters=7, random_state=0).fit(iris.data)
kmeans.cluster_centers_

array([[7.475     , 3.125     , 6.3       , 2.05      ],
       [5.24285714, 3.66785714, 1.5       , 0.28214286],
       [5.53214286, 2.63571429, 3.96071429, 1.22857143],
       [6.02777778, 2.73333333, 5.02777778, 1.79444444],
       [6.56818182, 3.08636364, 5.53636364, 2.16363636],
       [6.43      , 2.94      , 4.59      , 1.435     ],
       [4.70454545, 3.12272727, 1.41363636, 0.2       ]])

In [30]:
kmeans.cluster_centers_[0,0]

7.475

In [31]:
#Q3
'''
Cluster boston dataset into 5 cluster (set random_state=0). What will be the cluster label of the 100th house (please look at labels[100]).
'''

import numpy as np
from sklearn.cluster import KMeans

from sklearn.datasets import load_boston
boston= load_boston()

kmeans = KMeans(n_clusters=5, random_state=0).fit(boston.data)

kmeans.labels_[100]

4

In [ ]:
#Q4
'''
Cluster boston dataset into the 5 clusters (set random_state=0). What will be the first value of the first cluster center vector (please see kmeans.cluster_centers_).
'''
import numpy as np
from sklearn.cluster import KMeans

from sklearn.datasets import load_boston
boston= load_boston()

kmeans = KMeans(n_clusters=5, random_state=0).fit(boston.data)
kmeans.cluster_centers_

array([[ 1.96320727e+00,  1.77635684e-15,  1.67081818e+01,
         9.09090909e-02,  7.07727273e-01,  5.91609091e+00,
         9.18181818e+01,  2.32369091e+00,  4.72727273e+00,
         3.86909091e+02,  1.70000000e+01,  1.87546364e+02,
         1.72127273e+01],
       [ 1.09105113e+01,  5.32907052e-15,  1.85725490e+01,
         7.84313725e-02,  6.71225490e-01,  5.98226471e+00,
         8.99137255e+01,  2.07716373e+00,  2.30196078e+01,
         6.68205882e+02,  2.01950980e+01,  3.71803039e+02,
         1.78740196e+01],
       [ 2.35398154e-01,  1.72596154e+01,  6.70953846e+00,
         7.69230769e-02,  4.84571923e-01,  6.47326538e+00,
         5.60657692e+01,  4.83767308e+00,  4.33846154e+00,
         2.74688462e+02,  1.78615385e+01,  3.88775654e+02,
         9.46638462e+00],
       [ 1.63460857e+01, -5.32907052e-15,  1.81000000e+01,
         1.38777878e-17,  6.66828571e-01,  6.07600000e+00,
         9.01257143e+01,  1.98833429e+00,  2.40000000e+01,
         6.66000000e+02,  2.02000000e

In [ ]:
kmeans.cluster_centers_[0,0]

1.9632072727272727

In [ ]:
#Q5
'''
Reduce boston dataset into 3 components by PCA. And apply kmeans (random_state=0) for 4 clusters. what will be the cluster label of the 10th house (see labels[10]).
'''
from sklearn.cluster import KMeans

from sklearn.datasets import load_boston
boston= load_boston()

from sklearn.decomposition import PCA
pca = PCA(n_components=3)
boston3D=pca.fit_transform(boston.data)

kmeans = KMeans(n_clusters=4, random_state=0).fit(boston3D)
kmeans.labels_[10]

0

Week06 - Test 05

Reduce iris data to 3 dimensions with PCA. And then apply kmeans on reduced iris data for 10 clusters (keep random_state =0). What will be the label of the last flower  

In [32]:
from sklearn.cluster import KMeans

from sklearn.datasets import load_iris
iris= load_iris()

from sklearn.decomposition import PCA
pca = PCA(n_components=3)
iris3D=pca.fit_transform(iris.data)

kmeans = KMeans(n_clusters=10, random_state=0).fit(iris3D)
kmeans.labels_

array([0, 7, 7, 7, 0, 8, 7, 0, 7, 7, 8, 0, 7, 7, 8, 8, 8, 0, 8, 0, 0, 0,
       7, 0, 0, 7, 0, 0, 0, 7, 7, 0, 8, 8, 7, 7, 0, 0, 7, 0, 0, 7, 7, 0,
       0, 7, 0, 7, 0, 0, 4, 4, 4, 3, 4, 3, 4, 5, 4, 3, 5, 3, 3, 4, 3, 4,
       3, 3, 9, 3, 1, 3, 9, 4, 4, 4, 4, 4, 4, 3, 3, 5, 3, 9, 3, 4, 4, 4,
       3, 3, 3, 4, 3, 5, 3, 3, 3, 4, 5, 3, 2, 1, 2, 2, 2, 6, 3, 6, 2, 6,
       2, 9, 2, 1, 1, 2, 2, 6, 6, 9, 2, 1, 6, 9, 2, 6, 9, 1, 2, 2, 6, 6,
       2, 9, 9, 6, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 9, 2, 2, 1], dtype=int32)

Cluster iris data for 10 clusters (keep random state =0). How many flower will be belongs to label 4 

In [33]:
from sklearn.cluster import KMeans

from sklearn.datasets import load_iris
iris= load_iris()

kmeans = KMeans(n_clusters=10, random_state=0).fit(iris.data)
kmeans.labels_

array([0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 5, 0, 0, 0, 5, 5, 5, 0, 5, 5, 5, 5,
       0, 0, 0, 0, 0, 5, 0, 0, 0, 5, 5, 5, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0,
       5, 0, 5, 0, 5, 0, 8, 8, 8, 9, 8, 3, 8, 7, 8, 9, 7, 3, 9, 3, 9, 8,
       3, 9, 3, 9, 1, 3, 1, 3, 3, 8, 8, 8, 3, 9, 9, 9, 9, 1, 3, 3, 8, 3,
       9, 9, 9, 3, 9, 7, 9, 3, 3, 3, 7, 9, 4, 1, 6, 4, 4, 2, 9, 6, 6, 2,
       4, 1, 4, 1, 1, 4, 4, 2, 2, 1, 4, 1, 2, 1, 4, 6, 1, 1, 4, 6, 6, 2,
       4, 1, 1, 2, 4, 4, 1, 4, 4, 4, 1, 4, 4, 4, 1, 4, 4, 1], dtype=int32)

In [34]:
sum(kmeans.labels_==4)

21

In [52]:
#Q1

from sklearn.cluster import KMeans

from sklearn.datasets import load_wine
wine= load_wine()

from sklearn.decomposition import PCA
pca = PCA(n_components=5)
wine3D=pca.fit_transform(wine.data)

kmeans = KMeans(n_clusters=8, random_state=0).fit(wine3D)
kmeans.labels_

array([0, 0, 3, 6, 7, 6, 3, 3, 0, 0, 6, 3, 3, 0, 6, 3, 3, 0, 6, 5, 7, 7,
       0, 0, 5, 5, 3, 3, 5, 0, 3, 6, 0, 3, 0, 5, 5, 0, 0, 7, 7, 0, 0, 2,
       5, 0, 0, 0, 0, 3, 0, 3, 3, 3, 0, 0, 0, 3, 3, 1, 2, 1, 2, 4, 4, 2,
       1, 1, 7, 7, 5, 4, 1, 0, 5, 4, 4, 1, 7, 1, 4, 7, 2, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 4, 4, 5, 2, 4, 2, 4, 7, 1, 4, 4, 2, 4, 1, 1, 4, 2,
       1, 4, 2, 4, 4, 4, 1, 4, 4, 1, 2, 1, 4, 4, 4, 4, 4, 1, 4, 2, 2, 1,
       1, 2, 2, 7, 7, 1, 2, 2, 2, 7, 1, 1, 5, 5, 4, 2, 2, 1, 1, 1, 4, 2,
       2, 7, 1, 5, 2, 2, 1, 2, 1, 2, 2, 1, 7, 2, 7, 2, 1, 1, 2, 7, 7, 5,
       5, 1], dtype=int32)

# Q1

load wine dataset. First apply PCA to reduce 3 dimension. Then apply kmeans (random_state=0) to produce 5 clusters.
What is the last example cluster label

Answer is 4


load wine dataset. First apply PCA to reduce 4 dimension. Then apply kmeans (random_state=0) to produce 10 clusters.
What is the last example cluster label

Answer is 6


load wine dataset. First apply PCA to reduce 2 dimension. Then apply kmeans (random_state=0) to produce 7 clusters.
What is the last example cluster label

Answer is 1

load wine dataset. First apply PCA to reduce 5 dimension. Then apply kmeans (random_state=0) to produce 8 clusters.
What is the first example cluster label

Answer is 0


















