# CH 06 Linear Regression

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression


X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [ ]:
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([5, 10])) - 3
y

array([12, 22, 27, 37])

In [ ]:
reg = LinearRegression().fit(X, y)
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([ 5., 10.])

In [ ]:
reg.intercept_

-2.9999999999999964

In [ ]:
reg.score(X, y)

1.0

In [ ]:
import pandas as pd
df=pd.DataFrame(X, columns=["x0","x1"])
df["y"]=y
df

x0  x1   y
0   1   1  12
1   1   2  22
2   2   2  27
3   2   3  37

In [ ]:
new_row={'x0':1,'x1':1,'y':2}
df=df.append(new_row, ignore_index=True)
df

x0  x1   y
0   1   1  12
1   1   2  22
2   2   2  27
3   2   3  37
4   1   1   2

In [ ]:
df.iloc[:,:2]

x0  x1
0   1   1
1   1   2
2   2   2
3   2   3
4   1   1

In [ ]:
df.y

0    12
1    22
2    27
3    37
4     2
Name: y, dtype: int64

In [ ]:
df.iloc[:,2]

0    12
1    22
2    27
3    37
4     2
Name: y, dtype: int64

In [ ]:
X=df.iloc[:,:2]
y=df.y
reg = LinearRegression().fit(X, y)


In [ ]:
reg.coef_, reg.intercept_

(array([ 5.        , 12.85714286]), -10.142857142857135)

In [ ]:
reg.score(X, y)

0.9217221135029354

In [ ]:
reg.coef_, reg.intercept_

(array([ 5.        , 12.85714286]), -10.142857142857135)

What about prediction !

In [ ]:
reg.predict(np.array([[1, 1]]))

array([7.71428571])

In [ ]:
reg.predict(np.array([[5, 7]]))

array([104.85714286])

In [ ]:
reg.predict([[0,0]])

array([-10.14285714])

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
from sklearn.datasets import load_boston
boston= load_boston()

In [ ]:
X= boston.data
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
X.shape

(506, 13)

In [ ]:
y=boston.target
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:
reg = LinearRegression().fit(X, y)

In [ ]:
reg.coef_

In [ ]:
reg.intercept_

In [ ]:
reg.score(X, y)

In [ ]:
reg.predict(X[0:5])

In [ ]:
X[:5]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00]])

In [ ]:
reg.predict(X[:5])

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423])

In [ ]:
new_house=[1,1,1,1,1,1,1,1,1,1,1,1,1]
reg.predict([new_house])

array([22.49909025])

In [ ]:
[1]*13

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
reg.predict([[1]*13])

array([22.49909025])

In [ ]:
boston.data[:50].shape

(50, 13)

In [ ]:
X=boston.data[:50]
y=boston.target[:50]
reg = LinearRegression().fit(X,y)
reg.score(X, y)

0.9033643512190536

In [ ]:
X=boston.data[:400]
y=boston.target[:400]
reg = LinearRegression().fit(X,y)
reg.score(X,y)

0.7338501200472262

In [ ]:
X_test=boston.data[400:500]
y_test=boston.target[400:500]

In [ ]:
reg.score(X, y) # training performance

0.7338501200472262

In [ ]:
reg.score(X_test, y_test) # test performance

-0.3799600110322791

# TEST

* Q1: Train a regression model using first 100 rows in boston data set, try to predict the following vector below


```
# This is formatted as code
[1]*13

```

In [ ]:
[1]*13

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
#q1
X=boston.data[:100]
y=boston.target[:100]
reg = LinearRegression().fit(X,y)

reg.predict([[1]*13])

array([-11.44890053])


* Q2: Train a regression model based on the first 5 columns of the entire dataset (instead of 13 columns) of Boston dataset. And predict the following vector


```
# This is formatted as code
[1]*5
```

In [ ]:
[ [1]*5 ]

[[1, 1, 1, 1, 1]]

In [ ]:
#q2
X=boston.data[:,:5]


y=boston.target


reg = LinearRegression().fit(X,y)

reg.predict([[1]*5])

array([30.54461512])

* Q3: Train a regression model based on the first 200 rows. What is **reg.intercept_ value**

In [ ]:
#q3
X=boston.data[:200]
y=boston.target[:200]
reg = LinearRegression().fit(X,y)
reg.intercept_

-11.576492015402486

* Q4 Train a regression model based on the entire rows but the last raw (except the last raw), try the predict the last row. What is the predicted value for the last?


In [ ]:
#q4
X=boston.data[:-1]
y=boston.target[:-1]
reg = LinearRegression().fit(X,y)
reg.predict([boston.data[-1]])

array([22.56289031])

* Q5 Train a regression model based on the first 400 rows of boston dataset. And compute score when evaluating your model on the rest of boston dataset 401-506  

In [ ]:
X=boston.data[:400]
y=boston.target[:400]

X_test=boston.data[400:]
y_test=boston.target[400:]


reg = LinearRegression().fit(X,y)
reg.score(X_test, y_test)

-0.3410244010040666