# Data Pre-processing

```
# This is formatted as code
```

## 1.Standardization

In [ ]:
from sklearn import preprocessing
import numpy as np

X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [ ]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [ ]:
import pandas as pd
pd.DataFrame(X_train)

0    1    2
0  1.0 -1.0  2.0
1  2.0  0.0  0.0
2  0.0  1.0 -1.0

In [ ]:
X_train.mean(axis=0), X_train.std(axis=0)

(array([1.        , 0.        , 0.33333333]),
 array([0.81649658, 0.81649658, 1.24721913]))

In [ ]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scaler.mean_,scaler.scale_

(array([1.        , 0.        , 0.33333333]),
 array([0.81649658, 0.81649658, 1.24721913]))

In [ ]:
X_scaled=scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [ ]:
preprocessing.StandardScaler().fit_transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [ ]:
X_scaled.mean(axis=0), X_scaled.std(axis=0)

(array([0., 0., 0.]), array([1., 1., 1.]))

* Q1

In [ ]:
# Q1 When you standardize the following array, what would be the value 11 at the first row 
array=[[ 11., -1.,  2., 4],
       [ 2.,  0.,  0., 3],
       [ 0.,  1., -1., 6]]
pd.DataFrame(array)

0    1    2  3
0  11.0 -1.0  2.0  4
1   2.0  0.0  0.0  3
2   0.0  1.0 -1.0  6

In [ ]:
preprocessing.StandardScaler().fit_transform(array)

array([[ 1.39346603, -1.22474487,  1.33630621, -0.26726124],
       [-0.48771311,  0.        , -0.26726124, -1.06904497],
       [-0.90575292,  1.22474487, -1.06904497,  1.33630621]])

## 2.Normalizer

In [ ]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
X_normalized = preprocessing.normalize(X)

X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [ ]:
q=preprocessing.normalize([[1,1,1]])
q

array([[0.57735027, 0.57735027, 0.57735027]])

In [ ]:
np.sum(q**2)

1.0000000000000002

In [ ]:
np.sum(q**2)

1.0000000000000002

In [ ]:
vec=np.array([2,3,1,1,1])
np.sqrt(np.sum(vec**2))

4.0

In [ ]:
q=preprocessing.normalize([[2,3,1,1,1]])
q

array([[0.5 , 0.75, 0.25, 0.25, 0.25]])

* Q2 

Transform the array [8,6,12,9,21] with normalize.
What value will we see instead of 21?

In [ ]:
q=preprocessing.normalize([[8,6,12,9,21]])
q

array([[0.28905175, 0.21678881, 0.43357762, 0.32518322, 0.75876084]])

## 3.Encoding categorical features¶

In [ ]:
import pandas as pd

X = [['male', 'from US', 'uses Safari'], 
     ['female', 'from Europe', 'uses Chrome'],
     ['female', 'from Europe', 'uses Firefox'],
     ['female', 'from Asia', 'uses Firefox'],
     ['male', 'from US', 'uses Chrome'],
     ]
pd.DataFrame(X)

0            1             2
0    male      from US   uses Safari
1  female  from Europe   uses Chrome
2  female  from Europe  uses Firefox
3  female    from Asia  uses Firefox
4    male      from US   uses Chrome

In [ ]:
enc = preprocessing.OneHotEncoder()
enc.fit(X)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [ ]:
enc.transform(X).toarray()

array([[0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0.]])

In [ ]:
enc.transform([["male","from Asia","uses Firefox"]]).toarray()

array([[0., 1., 1., 0., 0., 0., 1., 0.]])

 * Q3
When you apply one hot-encoding for the followign data, how many columns we will have

| Category |    Type     | Color |
|----------|:-------------:|------:|
| A | import  | Blue | 
| A | export   |  Blue |
| B | import | Black |
| B | export | Red |
| B | export | Blue |


In [ ]:
7

7

## 4.Discretization

In [ ]:
# Discretization

In [ ]:
X = np.array([[ 3.,  5., 15.2 ],
              [  0., 9., 14.1 ],
              [  10.,9., 14.8 ],
              [  1., 11, 1 ],
              [  0., 6., 14 ],
              [  0., 3., 4 ],
              [  16.,3., 11.2 ],
              [  16.,3., 15.1 ]])

est = preprocessing.KBinsDiscretizer(encode='ordinal').fit(X)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)


In [ ]:
preprocessing.KBinsDiscretizer?

In [ ]:
est.transform(X)

array([[1., 1., 4.],
       [0., 3., 2.],
       [2., 3., 3.],
       [1., 3., 0.],
       [0., 1., 2.],
       [0., 0., 0.],
       [3., 0., 1.],
       [3., 0., 4.]])

* Q4
Discretize the following array.  How many bins I will see in the first column


```
X = np.array([[ 7.,  5., 15 ],
              [ 3.,  15., 15 ],
              [ -3.,  15., 5 ],
              [ 13.,  5., 15 ],
              [ 3.,  5., 15 ],
              [  0., 9., 14 ],
              [  10.,9., 14 ],
              [  1., 11, 1 ],
              [  0., 6., 14 ],
              [  0., 3., 4 ],
              [  16.,3., 11 ]])


```




In [ ]:
X = np.array([[ 7.,  5., 15 ],
              [ 3.,  15., 15 ],
              [ -3.,  15., 5 ],
              [ 13.,  5., 15 ],
              [ 3.,  5., 15 ],
              [  0., 9., 14 ],
              [  10.,9., 14 ],
              [  1., 11, 1 ],
              [  0., 6., 14 ],
              [  0., 3., 4 ],
              [  16.,3., 11 ]])

preprocessing.KBinsDiscretizer(encode='ordinal').fit_transform(X)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)


array([[3., 1., 2.],
       [3., 3., 2.],
       [0., 3., 1.],
       [4., 1., 2.],
       [3., 1., 2.],
       [1., 2., 2.],
       [4., 2., 2.],
       [2., 3., 0.],
       [1., 1., 2.],
       [1., 0., 0.],
       [4., 0., 1.]])

## 5.Missing Value Imputer

In [ ]:
import scipy.sparse as sp
import numpy as np
from sklearn.impute import SimpleImputer

X = np.array([[1, 2], 
              [0, 4], 
              [8, 6],
              [-1,-1],
              [9,-1],
              [-1,2]])

imp = SimpleImputer(missing_values=-1, strategy='mean')
imp.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=-1, strategy='mean', verbose=0)

In [ ]:
imp.transform([[-1,-1]])

array([[4.5, 3.5]])

In [ ]:
imp.transform(X)

array([[1. , 2. ],
       [0. , 4. ],
       [8. , 6. ],
       [4.5, 3.5],
       [9. , 3.5],
       [4.5, 2. ]])

In [ ]:
X_test = np.array([[-1, 2], 
                   [6, -1], 
                   [7, 6]])
imp.transform(X_test)

array([[4.5, 2. ],
       [6. , 3.5],
       [7. , 6. ]])

* Q5

Train a missing imputer using with this array and assign -1 as missing value
```
X = np.array([[1, 2], 
              [0, 12], 
              [8, 6]])
```


apply this to 
```
[[4,-1]]
```

In [ ]:
X = np.array([[1, 2], 
              [0, 12], 
              [8, 6]])
imp = SimpleImputer(missing_values=-1, strategy='mean')
imp.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=-1, strategy='mean', verbose=0)

In [ ]:
imp.transform([[4,-1]])

array([[4.        , 6.66666667]])

In [45]:
from sklearn.datasets import load_iris
iris= load_iris()
q=preprocessing.StandardScaler().fit_transform(iris.data)
q[0,0]

-0.9006811702978099

In [48]:
pd.DataFrame(iris.data).corr()

0         1         2         3
0  1.000000 -0.117570  0.871754  0.817941
1 -0.117570  1.000000 -0.428440 -0.366126
2  0.871754 -0.428440  1.000000  0.962865
3  0.817941 -0.366126  0.962865  1.000000