# Q1.A

Take the boston dataset and compute how many houses satistfying the following condition
* AGE>70 and RM<6.4

Here is the hint to load data and use it within pandas frame work

```
import pandas as pd
from sklearn.datasets import load_boston
boston= load_boston()
df=pd.DataFrame(boston.data, columns=boston.feature_names)
```



In [160]:
import pandas as pd
from sklearn.datasets import load_boston
boston= load_boston()
df=pd.DataFrame(boston.data, columns=boston.feature_names)
df

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [161]:
from sklearn.datasets import load_boston
boston= load_boston()

In [162]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [163]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [164]:
import pandas as pd
df=pd.DataFrame(boston.data, columns=boston.feature_names) 

In [181]:
df2=df[(df.AGE>70) & (df.RM<6.4)]

In [182]:
df2.shape

(195, 13)

## Q1.B

Sort the Boston House data by TAX in **descending order** and find the value of **NOX** of the first row in the sorted data

## Solution

In [183]:
df2.sort_values('TAX', ascending=False).iloc[0,:]

CRIM         0.18337
ZN           0.00000
INDUS       27.74000
CHAS         0.00000
NOX          0.60900
RM           5.41400
AGE         98.30000
DIS          1.75540
RAD          4.00000
TAX        711.00000
PTRATIO     20.10000
B          344.05000
LSTAT       23.97000
Name: 489, dtype: float64

# Q2

Train a missing value imputer (see chapter 03), from boston data set. Use -1 for missing_values and apply mean strategy. Try to predic the value of -1 for the following house.
```
# This is formatted as code
a_home=[-1, 18.0, 2.31, 0.0, 0.538, 6.575, 65.2, 4.09, 1.0, 296.0, 15.3, 396.9, 4.98]

```



In [151]:
import numpy as np
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=-1, strategy='mean')
imp.fit(boston.data)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=-1, strategy='mean', verbose=0)

In [152]:
a_home=[-1, 18.0, 2.31, 0.0, 0.538, 6.575, 65.2, 4.09, 1.0, 296.0, 15.3, 396.9, 4.98]

In [153]:
imp.transform([a_home])

array([[  3.61352356,  18.        ,   2.31      ,   0.        ,
          0.538     ,   6.575     ,  65.2       ,   4.09      ,
          1.        , 296.        ,  15.3       , 396.9       ,
          4.98      ]])

# Q3

Take the first 50 houses and apply PCA with the number of components of 2.
What would be the first component of the last house in the set.


In [154]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
boston50_2D=pca.fit_transform(boston.data[:50])

In [155]:
boston50_2D

array([[ -4.7804047 , -19.87008588],
       [-31.29156929,  -2.2397331 ],
       [-37.46560349,   8.6632907 ],
       [-58.60214121,  22.53595814],
       [-55.9024693 ,  17.11495376],
       [-52.18263765,  17.41965508],
       [  7.57443543, -26.31519198],
       [ 20.90730969, -40.01398925],
       [ 29.89639362, -33.83131506],
       [ 22.17690011, -27.56095829],
       [ 22.83983183, -35.81687217],
       [ 14.31362369, -34.26279189],
       [ -1.65405593, -10.69614723],
       [  2.70440809, -23.39765686],
       [ 23.42505869, -19.66572099],
       [  1.07539216, -20.14771067],
       [ -6.25316697,  -1.63665082],
       [ 18.52009584, -23.94712278],
       [ 56.45502446,  72.73992639],
       [ 10.10100789, -22.02155804],
       [ 32.75332866, -22.9915387 ],
       [ 18.39247194, -31.67767142],
       [ 17.3739216 , -36.3417637 ],
       [ 22.69489735, -38.01372367],
       [ 19.7790659 , -35.24903988],
       [ 70.65992266,  40.39572764],
       [ 28.39692392, -19.76016534],
 

# Q4
## Q4.A

Apply kmeans to the boston dataset to get 4 clusters (keep random_state as 0). What is the label of the last house.

In [184]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=4, random_state=0).fit(boston.data)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0,
       0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3,

In [185]:
df=pd.DataFrame(boston.data, columns=boston.feature_names)

In [186]:
df["label"]= kmeans.labels_

# Q4.B

Take a subset of boston houses with cluster labels 0 (which you clustered in the previous step (Question Q4.A), let us name it **data0**. How many rows in **data0**  satisfy the following condition
* CRIM> 1.0 

In [187]:
df3= df[df.label==0]
df3[df3.CRIM>1.0].shape

(10, 14)